#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR

export MAVEN_OPTS=-Xms384m -Xmx412m --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} --logging.file=${OPENSHIFT_LOG_DIR}app.log --spring.profiles.active=openshift

$M2/mvn spring-boot:run
